# Generated by Django 3.2.9 on 2021-12-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoallpoxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProxy',
        ),
        migrations.CreateModel(
            name='VideoPublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published video',
                'verbose_name_plural': 'Published videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
